# Generated by Django 4.0.4 on 2022-05-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triviya_cards_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
    ]
